APP           :=  app
CXX_VER       :=  14
DEBUG         :=  0
SHOW_WARNING  :=  0



ifeq (, $(shell which bear))
BEARCMD       :=
else
ifeq (bear 3.0.18, $(shell bear --version))
BEARCMD       := bear --output config/compile_commands.json --
else
BEARCMD       := bear -o config/compile_commands.json
endif
endif

